declare const _default: typeof __VLS_export;
export default _default;
declare const __VLS_export: import("vue").DefineComponent<{}, {}, {
    musicDetail: {};
    musicUrl: string;
    musicList: never[];
    currentMusicIndex: number;
    drawer: boolean;
    duration: string;
    currentTime: number;
    timeProgress: number;
    volume: number;
    isMuted: boolean;
    hasDrawerOpend: boolean;
    likeMuiscList: never[];
    isUserLikeCurrentMusic: boolean;
    recondInfo: string;
    playType: string;
}, {}, {
    getMusicDetail(id: any): Promise<void>;
    likeMusic(id: any, like: any): Promise<void>;
    getLikeMusicList(): Promise<void>;
    changePlayState(): void;
    playMusic(): void;
    pauseMusic(): void;
    changeState(state: any): void;
    getMusicDetailFromMusicList(): void;
    changeMusic(type: any, id: any): void;
    clickRow(row: any): void;
    timeupdate(): void;
    changeProgress(e: any): void;
    changeVolume(e: any): void;
    changeMutedState(): void;
    handleDrawerListDOM(currentIndex: any, lastIndex: any): void;
    openDrawer(): void;
    getIsUserLikeCurrentMusic(): void;
    likeIt(): Promise<void>;
    downloadCurrentMusic(): void;
    goToSingerDetail(): void;
}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
