/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminButton: typeof import('./components/admin/AdminButton.vue')['default']
    AdminInput: typeof import('./components/admin/AdminInput.vue')['default']
    AdminSelect: typeof import('./components/admin/AdminSelect.vue')['default']
    DailyLife: typeof import('./components/admin/dataStatistics/DailyLife.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconFontSymbol: typeof import('./components/IconFontSymbol.vue')['default']
    MusicianNumDataCard: typeof import('./components/admin/dataStatistics/MusicianNumDataCard.vue')['default']
    MyRecord: typeof import('./components/admin/dataStatistics/MyRecord.vue')['default']
    PlayListNumDataCard: typeof import('./components/admin/dataStatistics/PlayListNumDataCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongsNumDataCard: typeof import('./components/admin/dataStatistics/SongsNumDataCard.vue')['default']
    SongsTypeAssign: typeof import('./components/admin/dataStatistics/SongsTypeAssign.vue')['default']
    UserNumDataCard: typeof import('./components/admin/dataStatistics/UserNumDataCard.vue')['default']
  }
}
