/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminButton: typeof import('./components/admin/AdminButton.vue')['default']
    AdminInput: typeof import('./components/admin/AdminInput.vue')['default']
    AdminSelect: typeof import('./components/admin/AdminSelect.vue')['default']
    CommentSection: typeof import('./components/user/CommentSection.vue')['default']
    DailyLife: typeof import('./components/admin/dataStatistics/DailyLife.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLineChart: typeof import('element-plus/es')['ElLineChart']
    ElLoadingIndicator: typeof import('element-plus/es')['ElLoadingIndicator']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FollowSection: typeof import('./components/user/FollowSection.vue')['default']
    IconFontSymbol: typeof import('./components/IconFontSymbol.vue')['default']
    LeftMenu: typeof import('./components/HomePage/LeftMenu.vue')['default']
    LikedSongs: typeof import('./components/user/LikedSongs.vue')['default']
    MusicCard: typeof import('./components/MusicCard.vue')['default']
    MusicianDynamic: typeof import('./components/user/musician/MusicianDynamic.vue')['default']
    MusicianIntro: typeof import('./components/user/musician/MusicianIntro.vue')['default']
    MusicianNumDataCard: typeof import('./components/admin/dataStatistics/MusicianNumDataCard.vue')['default']
    MusicianWorks: typeof import('./components/user/musician/MusicianWorks.vue')['default']
    MusicListItem: typeof import('./components/MusicListItem.vue')['default']
    MusicStatistics: typeof import('./components/user/MusicStatistics.vue')['default']
    MyRecord: typeof import('./components/admin/dataStatistics/MyRecord.vue')['default']
    PlayListNumDataCard: typeof import('./components/admin/dataStatistics/PlayListNumDataCard.vue')['default']
    PlaylistSection: typeof import('./components/user/PlaylistSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongsNumDataCard: typeof import('./components/admin/dataStatistics/SongsNumDataCard.vue')['default']
    SongsTypeAssign: typeof import('./components/admin/dataStatistics/SongsTypeAssign.vue')['default']
    TagBar: typeof import('./components/TagBar.vue')['default']
    TopHeader: typeof import('./components/HomePage/TopHeader.vue')['default']
    UserHeader: typeof import('./components/user/UserHeader.vue')['default']
    UserNumDataCard: typeof import('./components/admin/dataStatistics/UserNumDataCard.vue')['default']
  }
}
